spring:
  application:
    name: account-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888},optional:configserver:http://config-server:8888"
  cloud:
    config:
      fail-fast: false

server:
  port: 8082


