spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: customer-service
              uri: lb://CUSTOMER-SERVICE
              predicates:
                - Path=/api/customers,/api/customers/**
              filters:
                - StripPrefix=1

            - id: account-service
              uri: lb://ACCOUNT-SERVICE
              predicates:
                - Path=/api/accounts,/api/accounts/**
              filters:
                - StripPrefix=1

server:
  port: ${SERVER_PORT:8080}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://service-registry:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${server.port:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
